### ISSUE TITLE
Cómo se pueden cambiar los términos y condiciones de las facturas, presupuestos, etc...

### ISSUE THREAD

**Issue by kapsule** [dev-kadira/Kadira#97]
Sebas de Telegram preguntaba como se podían modificar los términos y condiciones de las facturas, presupuestos, etc... Para poder editar este contenido, existen 2 opciones.

1. Desde los ajustes del sistema (Settings \ Inventory \ Terms & Conditions)

![image](https://github.com/dev-kadira/Kadira/assets/3903687/37837946-a895-4a6f-9fc0-af224207566d)

3. La otra opción es directamente la base de datos. En este caso, debemos modificar la tabla vtiger_inventory_tandc.

![image](https://github.com/dev-kadira/Kadira/assets/3903687/2f9675f4-6e14-45c1-9f30-ef375d8ebec7)

Espero que os sea de ayuda 👍

**Comment by Tupax** [comment]
Gracias! Aqui modifique para tener richtext, agarrar con cuidado que no esta muy probado,,,

layouts/v7/modules/Settings/Vtiger/resources/TermsAndConditionsEdit.js

`/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is: vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/

Vtiger.Class("Settings_Vtiger_TermsAndConditionsEdit_Js", {}, {
    //Contains Terms and Conditions container
    container: false,
    ckEditorInstance: null,

    //return the container of Terms and Conditions
    getContainer: function () {
        if (this.container === false) {
            this.container = jQuery('#TermsAndConditionsContainer');
        }
        return this.container;
    },
    init: function () {
        this.addComponents();
    },
    addComponents: function () {
        this.addComponent('Vtiger_Index_Js');
    },
    /*
     * Function to save the Terms & Conditions content
     */
    saveTermsAndConditions: function (text) {
        var aDeferred = jQuery.Deferred();
        var selectedModule = jQuery('#TermsAndConditionsContainer select.selectModule').val();
        var params = {
            'module': app.getModuleName(),
            'parent': app.getParentModuleName(),
            'action': 'TermsAndConditionsAjax',
            'tandc': text,
            'mode': 'save',
            'type': selectedModule
        };
        app.request.post({ "data": params }).then(
            function (error, data) {
                if (error === null) {
                    aDeferred.resolve();
                } else {
                    aDeferred.reject();
                }
            });
        return aDeferred.promise();
    },
    /*
     * Function to register keyUp event for text area to show save button
     */
    registerKeyUpEvent: function () {
        var thisInstance = this;
        var container = thisInstance.getContainer();
        container.find('.TCContent').keyup(function (e) {
            jQuery('.saveTC', container).removeClass('hide');
        });
    },

    registerSelectModuleEvent: function () {
        var thisInstance = this;
        var container = thisInstance.getContainer();
        var textAreaElement = jQuery('.TCContent', container);

        container.find('.selectModule').on('change', function (e) {
            var type = jQuery(e.currentTarget).val();

            var params = {
                'module': app.getModuleName(),
                'parent': app.getParentModuleName(),
                'action': 'TermsAndConditionsAjax',
                'mode': 'getModuleTermsAndConditions',
                'type': type
            };

            app.request.post({ "data": params }).then(function (err, data) {
                if (err === null) {
                    var newContent = typeof data === 'object' ? data.result : data;

                    for (var instance in CKEDITOR.instances) {
                        CKEDITOR.instances[instance].destroy();
                    }
                    textAreaElement.val(newContent); 
                    thisInstance.ckEditorInstance = CKEDITOR.replace(textAreaElement[0]);

                    jQuery('.saveTC', container).removeClass('hide');
                }
            });
        });
    },


    registerEvents: function () {
        var thisInstance = this;

        var container = thisInstance.getContainer();
        var textAreaElement = jQuery('.TCContent', container);
        var ckEditorInstance = CKEDITOR.replace(textAreaElement[0]);
        var saveButton = jQuery('.saveTC', container);

        //register text area fields to autosize
        thisInstance.registerKeyUpEvent();
        thisInstance.registerSelectModuleEvent();

        //Register click event for save button
        saveButton.click(function (e) {
            saveButton.addClass('hide');
            var content = thisInstance.ckEditorInstance.getData();
            console.log(content); 

            thisInstance.saveTermsAndConditions(content).then(
                function (data) {
                    console.log(data);
                    thisInstance.registerKeyUpEvent();
                    var message = app.vtranslate('JS_TERMS_AND_CONDITIONS_SAVED')
                    app.helper.showSuccessNotification({ 'message': message });
                });
        });

        var instance = new Settings_Vtiger_Index_Js();
        instance.registerBasicSettingsEvents();
        console.log(app.getModuleName());
    }

});
`

**Comment by kapsule** [comment]
Perfecto!!! Gracias por el aporte @Tupax.

Voy a preparar un PR y lo subo a la demo de Kadira para poder testear. Recuerda que si tienes mejoras de este tipo puedes aportar tus PR.
